const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||path.join(process.env.CODEX_HOME||path.join(require('node:os').homedir(),'.codex'),'skills/develop-web-game/node_modules/playwright'));
const url=process.env.HEXLAND_URL||'http://127.0.0.1:5211',out=process.env.HEXLAND_EVIDENCE||path.resolve(__dirname,'../../.visual-review/next-trio/hexland/verification');fs.mkdirSync(out,{recursive:true});
const report={checks:[],errors:[]};function check(name,value){assert.ok(value,name);report.checks.push(name)}
async function state(p){return p.evaluate(()=>JSON.parse(render_game_to_text()))}async function tick(p,ms=1000){await p.evaluate(ms=>advanceTime(ms),ms)}
async function clickFocus(p){await p.evaluate(()=>document.activeElement.click())}
async function fixture(p,kind='main'){
 await p.evaluate(kind=>{let s=HL.Game.newGame({seed:428});while(s.phase==='setup'){let p=HL.Game.currentSetupPlayer(s);HL.Game.placeInitialSettlement(s,HL.AI.pickInitialSettlement(s,p.idx));HL.Game.placeInitialRoad(s,HL.AI.pickInitialRoad(s,p.idx));}s.currentPlayerIdx=0;s.turnState='main';let p=s.players[0];
  if(kind==='roll')s.turnState='roll';
  if(kind==='rich')for(let r of HL.Game.RES){s.bank[r]-=6-p.hand[r];p.hand[r]=6;}
  if(kind==='discard'){p.hand={wood:8,brick:0,sheep:0,wheat:0,ore:0};s.turnState='robber-discard';s.discardCurrent={idx:0,need:4};s.discardQueue=[];s.robberMover=0;}
  if(kind==='road'){p.devHand.road=1;}
  if(kind==='plenty'){p.devHand.plenty=1;s.bank={wood:1,brick:1,sheep:0,wheat:0,ore:0};}
  if(kind==='one-plenty'){p.devHand.plenty=1;s.bank={wood:1,brick:0,sheep:0,wheat:0,ore:0};}
  if(kind==='knight'){p.devHand.knight=1;s.turnState='roll';}
  if(kind==='ai-road'){s=HL.Game.newGame({seed:428});let i=s.players.findIndex(p=>p.isAI);s.setupOrder=[i,(i+1)%4,(i+2)%4,(i+3)%4,(i+3)%4,(i+2)%4,(i+1)%4,i];HL.Game.placeInitialSettlement(s,HL.AI.pickInitialSettlement(s,i));}
  if(kind==='ai-turn'){s.currentPlayerIdx=1;s.turnState='roll';}
  if(kind==='human-trade'){s.players[1].isAI=false;p.hand.wood=2;s.players[1].hand.ore=2;}
  if(kind==='fourteenth-road'){p.roads={};let others=new Set(s.players.slice(1).flatMap(q=>Object.keys(q.roads)));for(let e of s.board.edges){if(!others.has(e.id)&&Object.keys(p.roads).length<14)p.roads[e.id]=true;}p.devHand.road=1;}
  __hexland.load(s);advanceTime(250);
 },kind);
}
(async()=>{let browser;try{
 browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:600,height:600},serviceWorkers:'block'}),p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));
 await p.goto(url+'/?test');check('Meta app capability and native 600 layout',await p.locator('meta[name=mrbd-web-app-capable]').getAttribute('content')==='yes'&&await p.evaluate(()=>document.getElementById('app').getBoundingClientRect().width===600));
 const legacy=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/legacy-v1.json'),'utf8'));await p.evaluate(raw=>localStorage.setItem('hexland_save_v1',JSON.stringify(raw)),legacy);await p.reload();let loaded=await p.evaluate(()=>{document.querySelector('[data-action=continue-game]').click();return __hexland.snapshot()});check('actual original-version local save continues without altering pieces or board',JSON.stringify(loaded.players)===JSON.stringify(legacy.players)&&JSON.stringify(loaded.board)===JSON.stringify(legacy.board));await p.goto(url+'/?test');
 await clickFocus(p);check('pinch opens setup with useful Begin focus',(await state(p)).screen==='setup'&&(await state(p)).focus.action==='start-game');await clickFocus(p);
 for(let i=0;i<200;i++){await tick(p,100);let s=await state(p);if(s.phase==='play')break;if(s.cursor){await clickFocus(p);await tick(p,200);if((await state(p)).cursor)await p.keyboard.press('Enter');}}
 check('pinch and Enter complete all setup pairs against real AI',(await state(p)).phase==='play'&&(await state(p)).players.every(p=>p.settlements.length===2&&p.roads.length===2));
 await fixture(p,'roll');await p.click('#btn-primary');await p.evaluate(()=>{for(let i=0;i<8;i++)document.getElementById('btn-primary').click()});await tick(p,600);check('rapid Roll activation creates one dice result',await p.evaluate(()=>__hexland.snapshot().diceHistory.length===1));
 await fixture(p,'rich');await p.click('#btn-menu');await p.click('[data-action=build-road]');let before=(await state(p)).hand;await p.keyboard.press('Escape');check('cancel road placement spends no resources',!(await state(p)).cursor&&JSON.stringify(before)===JSON.stringify((await state(p)).hand));
 await p.click('#btn-menu');await p.click('[data-action=build-road]');let oldRoads=(await state(p)).players[0].roads.length;await clickFocus(p);check('focused board click places one connected road',(await state(p)).players[0].roads.length===oldRoads+1);
 await p.click('#btn-menu');await p.click('[data-action=trade-bank]');await p.click('[data-action=bank-give-pick][data-res=wood]');await p.click('[data-action=bank-recv-pick][data-res=ore]');let hand=(await state(p)).hand;await p.click('[data-action=confirm-bank-trade]');check('bank trade returns to board and transfers resources once',(await state(p)).screen==='game'&&(await state(p)).hand.ore===hand.ore+1);
 await fixture(p,'discard');for(let i=0;i<4;i++)await p.click('[data-action=discard-pick][data-res=wood]');check('four cards of one resource can be selected for discard',await p.locator('#discard-count').textContent()==='4');await p.reload();await p.click('[data-action=continue-game]');await tick(p,300);check('discard selection survives reload and Continue',await p.locator('#discard-count').textContent()==='4');await p.click('[data-action=confirm-discard]');await tick(p,500);check('discard returns exactly four wood and enters mandatory robber move',(await state(p)).hand.wood===4&&(await state(p)).cursor?.mode==='tile-pick');
 let robber=(await state(p)).robber;await clickFocus(p);await tick(p,100);let ss=await state(p);if(ss.popover){await clickFocus(p);}check('robber selection progresses without requiring an unavailable Back gesture',(await state(p)).robber!==robber&&(await state(p)).turnState==='main');
 await fixture(p,'road');await p.click('#btn-menu');await p.click('[data-action=play-dev]');await p.click('[data-action=play-dev-road]');let n=(await state(p)).players[0].roads.length;await clickFocus(p);await tick(p,300);await clickFocus(p);await tick(p,300);check('Road Building places exactly two free roads and returns to main',(await state(p)).players[0].roads.length===n+2&&(await state(p)).turnState==='main');
 await fixture(p,'plenty');await p.click('#btn-menu');await p.click('[data-action=play-dev]');await p.click('[data-action=play-dev-plenty]');await p.click('[data-action=pick-plenty][data-res=wood]');check('first Plenty pick reserves the last bank card',await p.locator('[data-action=pick-plenty][data-res=wood]').isDisabled());await p.click('#action-menu .required-pause');await clickFocus(p);await tick(p,100);check('required card choices have a reachable Menu and resume the pending pick',(await state(p)).turnState==='pick-plenty'&&await p.locator('[data-action=pick-plenty][data-res=wood]').isDisabled());await p.reload();await p.click('[data-action=continue-game]');await tick(p,300);check('Plenty first pick survives reload',await p.locator('[data-action=pick-plenty][data-res=wood]').isDisabled());await p.click('[data-action=pick-plenty][data-res=brick]');check('Plenty resolves exact available resources',(await state(p)).turnState==='main'&&(await state(p)).bank.wood===0&&(await state(p)).bank.brick===0);
 await fixture(p,'one-plenty');await p.click('#btn-menu');await p.click('[data-action=play-dev]');await p.click('[data-action=play-dev-plenty]');await p.click('[data-action=pick-plenty][data-res=wood]');check('one-card bank ends Plenty without a second-choice softlock',(await state(p)).turnState==='main');
 await fixture(p,'fourteenth-road');await p.click('#btn-menu');await p.click('[data-action=play-dev]');await p.click('[data-action=play-dev-road]');await clickFocus(p);await tick(p,300);check('Road Building with only one piece left ends safely at 15 roads',(await state(p)).players[0].roads.length===15&&(await state(p)).turnState==='main');
 await fixture(p,'knight');await p.click('#btn-menu');await p.click('[data-action=play-dev]');await p.click('[data-action=play-dev-knight]');await clickFocus(p);if((await state(p)).popover)await clickFocus(p);check('pre-roll Knight restores Roll Dice',(await state(p)).turnState==='roll');
 await fixture(p,'ai-road');let setup=await p.evaluate(()=>__hexland.snapshot()),idx=setup.setupOrder[0],settlements=Object.keys(setup.players[idx].settlements);await tick(p,350);let resumed=await p.evaluate(()=>__hexland.snapshot());check('AI save between settlement and road resumes road without duplicate town',Object.keys(resumed.players[idx].settlements).join()===settlements.join()&&Object.keys(resumed.players[idx].roads).length===1);
 await fixture(p,'ai-turn');await p.click('#btn-pause');let frozen=await p.evaluate(()=>JSON.stringify(__hexland.snapshot()));await tick(p,50000);check('Menu pauses delayed AI work during its turn',await p.evaluate(()=>JSON.stringify(__hexland.snapshot()))===frozen);await clickFocus(p);await tick(p,25000);check('Resume restarts paused AI and returns to the human',(await state(p)).screen==='game'&&(await state(p)).currentPlayer===0);
 await fixture(p,'rich');let saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('hexland_save_v1')));await p.click('#btn-pause');await p.click('[data-action=save-exit]');await p.click('[data-action=continue-game]');await tick(p,300);let restored=await p.evaluate(()=>__hexland.snapshot());check('save-and-menu Continue preserves complete played game',JSON.stringify(restored.players)===JSON.stringify(saved.players)&&JSON.stringify(restored.board)===JSON.stringify(saved.board));
 await fixture(p,'human-trade');await p.click('#btn-menu');await p.click('[data-action=trade-players]');await p.click('[data-action=pt-give-inc][data-res=wood]');await p.click('[data-action=pt-recv-inc][data-res=ore]');await p.click('[data-action=propose-trade]');let offerHand=(await state(p)).hand;await p.click('[data-action=accept-trade-with][data-with="1"]');check('pass-and-play trade waits for recipient approval',await p.locator('#trade-consent').isVisible()&&JSON.stringify((await state(p)).hand)===JSON.stringify(offerHand));await p.click('[data-action=consent-decline]');check('declining a human trade keeps all resources',JSON.stringify((await state(p)).hand)===JSON.stringify(offerHand));await p.click('[data-action=accept-trade-with][data-with="1"]');await clickFocus(p);check('recipient confirmation completes the trade once',(await state(p)).screen==='game'&&(await state(p)).hand.wood===offerHand.wood-1&&(await state(p)).hand.ore===offerHand.ore+1);
 await fixture(p,'rich');
 await p.click('#btn-menu');for(let i=0;i<25;i++){await p.keyboard.press(i%2?'ArrowDown':'Tab');check('modal focus stays visible '+i,await p.evaluate(()=>document.activeElement.getClientRects().length>0&&document.activeElement.closest('#action-menu')!==null));}await p.keyboard.press('Escape');
 const builds=(await state(p)).render.staticBuilds;await p.click('#btn-players');await p.click('#players-menu [data-action=close-popover]');check('HUD and overlays reuse the cached static landscape',(await state(p)).render.staticBuilds===builds);
 await fixture(p,'roll');let turns=0,longSteps=0;
 while(turns<30&&longSteps++<300){let s=await state(p);if(s.phase==='over')break;
  if(s.screen==='discard'){await p.evaluate(()=>{let s=__hexland.snapshot(),sel=s._discardSelected,need=s.discardCurrent.need;for(let r of HL.Game.RES){let left=need-Object.values(sel).reduce((a,b)=>a+b,0);let n=Math.min(left,s.players[s.discardCurrent.idx].hand[r]-sel[r]);for(let i=0;i<n;i++){document.querySelector('[data-action=discard-pick][data-res='+r+']').click();sel[r]++;}}document.getElementById('btn-confirm-discard').click();});await tick(p,300);continue;}
  if(s.cursor){await p.locator('#board-control').focus();await clickFocus(p);await tick(p,500);continue;}
  if(s.popover){await clickFocus(p);await tick(p,500);continue;}
  if(s.currentPlayer!==0){await tick(p,25000);continue;}
  if(s.turnState==='roll'){await p.click('#btn-primary');await tick(p,1500);continue;}
  if(s.turnState==='main'){await p.click('#btn-primary');turns++;await tick(p,25000);continue;}
  throw Error('Unresolved long-session phase: '+JSON.stringify(s));
 }
 let long=await p.evaluate(()=>__hexland.snapshot());check('30 human turns with real AI have no stuck phases or duplicate production',turns>=30||long.phase==='over');check('long session conserves every resource across bank/AI/robber',Object.keys(long.bank).every(r=>long.bank[r]+long.players.reduce((n,q)=>n+q.hand[r],0)===19));report.longSession={humanTurns:turns,diceRolls:long.diceHistory.length,phase:long.phase,steps:longSteps};await fixture(p,'rich');
 await p.screenshot({path:path.join(out,'game-600.png')});await p.click('#btn-pause');await p.screenshot({path:path.join(out,'pause-600.png')});
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}),phone=await mobile.newPage();phone.on('pageerror',e=>report.errors.push(e.message));await phone.goto(url+'/?test');await fixture(phone,'rich');await phone.waitForTimeout(100);let fit=await phone.evaluate(()=>{let r=document.getElementById('app').getBoundingClientRect();return{left:r.left,right:r.right,bottom:r.bottom,viewport:visualViewport.width,buttons:[...document.querySelectorAll('.action-strip button')].map(b=>b.getBoundingClientRect().height)}});check('real 390 phone fits and all action buttons are at least 44px',fit.left>=0&&fit.right<=391&&fit.bottom<=845&&fit.buttons.every(h=>h>=44));await phone.screenshot({path:path.join(out,'game-phone.png')});await phone.tap('#btn-menu');await phone.tap('[data-action=build-road]');let cs=await state(phone);let target=phone.locator('[data-eid="'+cs.cursor.id+'"].edge-hit');await target.tap({force:true});check('phone touch places one road',(await state(phone)).players[0].roads.length===3);await mobile.close();
 check('no browser runtime errors',report.errors.length===0);report.final=await state(p);
 }catch(error){report.failure=error.stack;process.exitCode=1;console.error(error)}finally{await browser?.close();report.passed=report.checks.length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failure:report.failure?.split('\n')[0],errors:report.errors}));}})();
