const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={window:{},console};vm.createContext(ctx);for(const f of ['board','ai','game'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/'+f+'.js'),'utf8'),ctx,{filename:f+'.js'});
const {Game:G,Board:B,AI}=ctx.window.HL,clean=x=>JSON.parse(JSON.stringify(x)),checks=[];
function test(name,fn){fn();checks.push(name)}
function game(seed=428){const s=G.newGame({seed});let steps=0;while(s.phase==='setup'&&steps++<8){const p=G.currentSetupPlayer(s);G.placeInitialSettlement(s,AI.pickInitialSettlement(s,p.idx));G.placeInitialRoad(s,AI.pickInitialRoad(s,p.idx));}assert.equal(s.phase,'play');s.currentPlayerIdx=0;s.turnState='main';return s}
function sum(s,r){return s.bank[r]+s.players.reduce((n,p)=>n+p.hand[r],0)}
function fund(s,p,r,n){s.bank[r]-=n-p.hand[r];p.hand[r]=n}
test('100 seeds complete lawful snake setup with conserved resources and unique pieces',()=>{for(let seed=1;seed<=100;seed++){let s=game(seed);assert.equal(s.board.tiles.length,19);assert.equal(s.board.vertices.length,54);assert.equal(s.board.edges.length,72);for(const p of s.players){assert.equal(Object.keys(p.settlements).length,2);assert.equal(Object.keys(p.roads).length,2)}for(const r of G.RES)assert.equal(sum(s,r),19);assert.equal(new Set(s.players.flatMap(p=>Object.keys(p.settlements))).size,8)}});
test('duplicate setup activation cannot place an extra settlement or award resources twice',()=>{let s=G.newGame({seed:6});let v=G.legalInitialSettlement(s)[0];G.placeInitialSettlement(s,v);let before=clean(s);assert.equal(G.placeInitialSettlement(s,v),false);assert.deepEqual(clean(s),before)});
test('building charges once, rejects occupied/disconnected edges and enforces roads limit',()=>{let s=game(),p=s.players[0];fund(s,p,'wood',4);fund(s,p,'brick',4);let id=B.legalRoadEdges(s.board,s.players,0)[0];assert.equal(G.buildRoad(s,id).ok,true);let before=clean(s);assert.equal(G.buildRoad(s,id).ok,false);assert.deepEqual(clean(s),before);let remote=s.board.edges.find(e=>!p.roads[e.id]&&!B.legalRoadEdges(s.board,s.players,0).includes(e.id));assert.equal(G.buildRoad(s,remote.id).ok,false);for(const r of G.RES)assert.equal(sum(s,r),19)});
test('bank trades honor ports, conserve cards and fail atomically when bank is empty',()=>{let s=game(),p=s.players[0];fund(s,p,'wood',8);let rate=B.playerPorts(s.board,p).wood||4,old=p.hand.wood;assert.equal(G.tradeWithBank(s,'wood','ore').ok,true);assert.equal(p.hand.wood,old-rate);for(const r of G.RES)assert.equal(sum(s,r),19);s.bank.ore=0;let before=clean(s);assert.equal(G.tradeWithBank(s,'wood','ore').ok,false);assert.deepEqual(clean(s),before)});
test('player trade is atomic and cannot charge twice after supplies run out',()=>{let s=game(),p=s.players[0],q=s.players[1];fund(s,p,'wood',1);fund(s,q,'ore',1);assert.equal(G.executePlayerTrade(s,0,1,{wood:1},{ore:1}).ok,true);let before=clean(s);assert.equal(G.executePlayerTrade(s,0,1,{wood:1},{ore:1}).ok,false);assert.deepEqual(clean(s),before);for(const r of G.RES)assert.equal(sum(s,r),19)});
test('repeated roll calls produce exactly one roll and cannot bypass robber obligations',()=>{let s=game();s.turnState='roll';s.rng=()=>.5;G.rollDice(s);let before=clean(s);assert.equal(G.rollDice(s).ok,false);assert.deepEqual(clean(s),before)});
test('new development cards wait until next turn and only one action card is playable',()=>{let s=game(),p=s.players[0];for(const r of ['sheep','wheat','ore'])fund(s,p,r,1);s.devDeck=['knight'];assert.equal(G.buyDev(s).ok,true);assert.equal(G.playDev(s,'knight').ok,false);G.endTurn(s);s.currentPlayerIdx=0;s.turnState='roll';assert.equal(G.playDev(s,'knight').ok,true);assert.equal(G.playDev(s,'knight').ok,false)});
test('all progress cards are usable before dice and restore the unrolled phase',()=>{for(const kind of ['mono','plenty','road']){let s=game(),p=s.players[0];p.devHand[kind]=1;s.turnState='roll';assert.equal(G.playDev(s,kind).ok,true);assert.equal(s._postDevState,'roll');if(kind==='mono')G.resolveMonopoly(s,'wood');if(kind==='plenty')G.resolvePlenty(s,['wood','wood']);if(kind!=='road')assert.equal(s.turnState,'roll')}});
test('plenty chooses available cards, handles a one-card bank and rejects duplicate unavailable picks',()=>{let s=game(),p=s.players[0];p.devHand.plenty=1;s.bank={wood:1,brick:0,sheep:0,wheat:0,ore:0};assert.equal(G.playDev(s,'plenty').ok,true);assert.deepEqual(clean(AI.chooseBestResources(s,p,2)),['wood']);assert.equal(G.resolvePlenty(s,['wood']).ok,true);assert.equal(s.turnState,'main');assert.equal(s.bank.wood,0);s=game();s.players[0].devHand.plenty=1;s.bank={wood:1,brick:1,sheep:0,wheat:0,ore:0};G.playDev(s,'plenty');let before=clean(s);assert.equal(G.resolvePlenty(s,['wood','wood']).ok,false);assert.deepEqual(clean(s),before)});
test('road building cannot consume a card when all 15 road pieces are used',()=>{let s=game(),p=s.players[0];p.roads=Object.fromEntries(s.board.edges.slice(0,15).map(e=>[e.id,true]));p.devHand.road=1;assert.equal(G.playDev(s,'road').ok,false);assert.equal(p.devHand.road,1)});
test('interrupted longest-road tie releases the award rather than picking first player',()=>{let s=game(),orig=B.longestRoadFor,lengths=[3,6,6,2];B.longestRoadFor=(_b,_p,i)=>lengths[i];try{s.longestRoadOwner=0;G.recomputeLongestRoad(s);assert.equal(s.longestRoadOwner,null);lengths=[3,7,6,2];G.recomputeLongestRoad(s);assert.equal(s.longestRoadOwner,1);lengths=[3,7,7,2];G.recomputeLongestRoad(s);assert.equal(s.longestRoadOwner,1)}finally{B.longestRoadFor=orig}});
test('victory is awarded on the winner’s own turn',()=>{let s=game();s.players[1].devHand.vp=10;assert.equal(G.checkWin(s),false);s.currentPlayerIdx=1;assert.equal(G.checkWin(s),true);assert.equal(s.winnerIdx,1)});
test('legacy save rebuilds references without changing resources, cards, geometry or pieces',()=>{let s=game();let raw=clean(s),restored=G.restore(raw);assert.ok(restored);assert.deepEqual(clean(restored),raw);assert.equal(restored.board.vertices[0],restored.board.verticesById[restored.board.vertices[0].id]);raw.players[0].hand.wood=-1;assert.equal(G.restore(raw),null)});
test('partial or malformed saves do not crash the restore path',()=>{for(const x of [null,{},[],{phase:'play'},Object.assign(clean(game()),{players:null})])assert.equal(G.restore(x),null)});
test('actual original-version save fixture is preserved exactly',()=>{const raw=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/legacy-v1.json'),'utf8'));const restored=G.restore(raw);assert.ok(restored);assert.deepEqual(clean(restored),raw)});
console.log(JSON.stringify({passed:checks.length,checks},null,2));
